[tools]
rotrieve = { source = "roblox/rotriever", version = "=0.5.4" }
selene = { source = "Roblox/Kampfkarren-selene", version = "0.25.0" }
stylua = { source = "Roblox/JohnnyMorganz-StyLua", version = "0.18.1" }
