[package]
name = "ChalkLua"
authors = [
    "Raymond Ng <rng@roblox.com>",
    "Chris Trzesniewski <k.trzesniewski@gmail.com>"
]
description = "A Luau port of the open source terminal string styling library."
repository = "https://github.com/Roblox/chalk-lua-internal"
keywords = ["color", "terminal", "string", "style"]

license = "MIT"
content_root = "src"
version = "0.2.1"

[dev_dependencies]
TestEZ = "github.com/roblox/testez@0.4.1"
